require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sources_users", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SourcesUser. As you add validations to SourcesUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SourcesUser.create! valid_attributes
      get sources_users_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sources_user = SourcesUser.create! valid_attributes
      get sources_user_url(sources_user)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sources_user_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      sources_user = SourcesUser.create! valid_attributes
      get edit_sources_user_url(sources_user)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SourcesUser" do
        expect {
          post sources_users_url, params: { sources_user: valid_attributes }
        }.to change(SourcesUser, :count).by(1)
      end

      it "redirects to the created sources_user" do
        post sources_users_url, params: { sources_user: valid_attributes }
        expect(response).to redirect_to(sources_user_url(SourcesUser.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SourcesUser" do
        expect {
          post sources_users_url, params: { sources_user: invalid_attributes }
        }.to change(SourcesUser, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post sources_users_url, params: { sources_user: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sources_user" do
        sources_user = SourcesUser.create! valid_attributes
        patch sources_user_url(sources_user), params: { sources_user: new_attributes }
        sources_user.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sources_user" do
        sources_user = SourcesUser.create! valid_attributes
        patch sources_user_url(sources_user), params: { sources_user: new_attributes }
        sources_user.reload
        expect(response).to redirect_to(sources_user_url(sources_user))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        sources_user = SourcesUser.create! valid_attributes
        patch sources_user_url(sources_user), params: { sources_user: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sources_user" do
      sources_user = SourcesUser.create! valid_attributes
      expect {
        delete sources_user_url(sources_user)
      }.to change(SourcesUser, :count).by(-1)
    end

    it "redirects to the sources_users list" do
      sources_user = SourcesUser.create! valid_attributes
      delete sources_user_url(sources_user)
      expect(response).to redirect_to(sources_users_url)
    end
  end
end
